[build-system]
requires = [
    "setuptools",
]
build-backend = "setuptools.build_meta"

[project]
name = "glodap"
description = "GLODAP downloader and importer in Python"
readme = "README.md"
requires-python = ">= 3.11"
dependencies = [
    "pandas>=3.0.3,<4",
    "pooch>=1.9.0,<2",
    "scipy>=1.17.1,<2",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
    "Natural Language :: English",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Chemistry",
    "Topic :: Scientific/Engineering :: Oceanography",
]
dynamic = ["version"]

[tool.setuptools.packages.find]
include = ["glodap*"]

[tool.setuptools.dynamic]
version = {attr = "glodap.__version__"}

[tool.ruff]
line-length = 79

[tool.ruff.lint.isort]
combine-as-imports = true
force-single-line = false
lines-after-imports = 2

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
]
